package uz.kmax.a4pic1word.gamelevel;

import uz.kmax.a4pic1word.R;

public class GameLevel {
    public int[] image1 = {
            R.drawable.level1_1,
            R.drawable.level2_1,
            R.drawable.level3_1,
            R.drawable.level4_1,
            R.drawable.level5_1,
            R.drawable.level6_1,
            R.drawable.level7_1,
            R.drawable.level8_1,
            R.drawable.level9_1,
            R.drawable.level10_1,
            R.drawable.level11_1,
            R.drawable.level12_1,
            R.drawable.level13_1,
            R.drawable.level14_1,
            R.drawable.level15_1,
            R.drawable.level16_1,
            R.drawable.level17_1,
            R.drawable.level18_1,
            R.drawable.level19_1,
            R.drawable.level20_1,
    };

    public int[] image2 = {
            R.drawable.level1_2,
            R.drawable.level2_2,
            R.drawable.level3_2,
            R.drawable.level4_2,
            R.drawable.level5_2,
            R.drawable.level6_2,
            R.drawable.level7_2,
            R.drawable.level8_2,
            R.drawable.level9_2,
            R.drawable.level10_2,
            R.drawable.level11_2,
            R.drawable.level12_2,
            R.drawable.level13_2,
            R.drawable.level14_2,
            R.drawable.level15_2,
            R.drawable.level16_2,
            R.drawable.level17_2,
            R.drawable.level18_2,
            R.drawable.level19_2,
            R.drawable.level20_2,
    };

    public int[] image3 = {
            R.drawable.level1_3,
            R.drawable.level2_3,
            R.drawable.level3_3,
            R.drawable.level4_3,
            R.drawable.level5_3,
            R.drawable.level6_3,
            R.drawable.level7_3,
            R.drawable.level8_3,
            R.drawable.level9_3,
            R.drawable.level10_3,
            R.drawable.level11_3,
            R.drawable.level12_3,
            R.drawable.level13_3,
            R.drawable.level14_3,
            R.drawable.level15_3,
            R.drawable.level16_3,
            R.drawable.level17_3,
            R.drawable.level18_3,
            R.drawable.level19_3,
            R.drawable.level20_3,
    };

    public int[] image4 = {
            R.drawable.level1_4,
            R.drawable.level2_4,
            R.drawable.level3_4,
            R.drawable.level4_4,
            R.drawable.level5_4,
            R.drawable.level6_4,
            R.drawable.level7_4,
            R.drawable.level8_4,
            R.drawable.level9_4,
            R.drawable.level10_4,
            R.drawable.level11_4,
            R.drawable.level12_4,
            R.drawable.level13_4,
            R.drawable.level14_4,
            R.drawable.level15_4,
            R.drawable.level16_4,
            R.drawable.level17_4,
            R.drawable.level18_4,
            R.drawable.level19_4,
            R.drawable.level20_4,
    };

    public int[] word = {
            R.string.word_level1, R.string.word_level2, R.string.word_level3, R.string.word_level4,
            R.string.word_level5, R.string.word_level6, R.string.word_level7, R.string.word_level8,
            R.string.word_level9, R.string.word_level10, R.string.word_level11, R.string.word_level12,
            R.string.word_level13, R.string.word_level14, R.string.word_level15, R.string.word_level16,
            R.string.word_level17, R.string.word_level18, R.string.word_level19, R.string.word_level20,
            R.string.word_level21, R.string.word_level22, R.string.word_level23, R.string.word_level24,
            R.string.word_level25, R.string.word_level26, R.string.word_level27, R.string.word_level28,
            R.string.word_level29, R.string.word_level30, R.string.word_level31, R.string.word_level32,
            R.string.word_level33, R.string.word_level34, R.string.word_level35, R.string.word_level36,
            R.string.word_level37, R.string.word_level38, R.string.word_level39, R.string.word_level40,
            R.string.word_level41, R.string.word_level42, R.string.word_level43, R.string.word_level44,
            R.string.word_level45, R.string.word_level46, R.string.word_level47, R.string.word_level48,
            R.string.word_level49, R.string.word_level50,
    };

    public int[] letter = {
            R.string.letter_level1, R.string.letter_level2, R.string.letter_level3, R.string.letter_level4,
            R.string.letter_level5, R.string.letter_level6, R.string.letter_level7, R.string.letter_level8,
            R.string.letter_level9, R.string.letter_level10, R.string.letter_level11, R.string.letter_level12,
            R.string.letter_level13, R.string.letter_level14, R.string.letter_level15, R.string.letter_level16,
            R.string.letter_level17, R.string.letter_level18, R.string.letter_level19, R.string.letter_level20,
            R.string.letter_level21, R.string.letter_level22, R.string.letter_level23, R.string.letter_level24,
            R.string.letter_level25, R.string.letter_level26, R.string.letter_level27, R.string.letter_level28,
            R.string.letter_level29, R.string.letter_level30, R.string.letter_level31, R.string.letter_level32,
            R.string.letter_level33, R.string.letter_level34, R.string.letter_level35, R.string.letter_level36,
            R.string.letter_level37, R.string.letter_level38, R.string.letter_level39, R.string.letter_level40,
            R.string.letter_level41, R.string.letter_level42, R.string.letter_level43, R.string.letter_level44,
            R.string.letter_level45, R.string.letter_level46, R.string.letter_level47, R.string.letter_level48,
            R.string.letter_level49, R.string.letter_level50,
    };
}
